### ISSUE TITLE
Update subscripts

### ISSUE THREAD

**Issue by AlexisRenchon** [SimonDanisch/UnicodeFun.jl#16]
Missing subscripts have just been added at https://github.com/ypsu/latex-to-unicode/blob/master/data/subscripts

and they should be added to https://github.com/SimonDanisch/UnicodeFun.jl/blob/master/src/sub_super_scripts.jl

**Comment by SimonDanisch** [comment]
Would you mind opening a PR ? :)

**Comment by AlexisRenchon** [comment]
Done! It was my first PR, so I might have done things wrong. Let me know how it looks!
