### ISSUE TITLE
Incorrect error message.

### ISSUE THREAD

**Issue by nathanrboyer** [SimonDanisch/UnicodeFun.jl#22]
The error should say "subscript".
```julia
julia> to_subscript("z")
ERROR: Char z doesn't have a unicode superscript

julia> to_latex("f\\_z")
ERROR: Char z doesn't have a unicode superscript
```

**Comment by SimonDanisch** [comment]
Small spelling mistakes like this are great to just be submitted as a PR instead of an issue ;)
One can directly edit all files here on GitHub to do fixes like this! :)

**Comment by nathanrboyer** [comment]
Sorry, I'm new to this.

**Comment by SimonDanisch** [comment]
No worries, thanks a lot! :)
